'use client'
import React from 'react';
import { useEffect, useState } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Destination, TravelPlan } from '@/types/travel'
import { generateItinerary } from '@/services/itineraryService'
import { Loader2, MapPin, CalendarDays, Sparkles } from 'lucide-react'

interface AiTravelSidebarProps {
  destination: Destination | null
  isOpen: boolean
  onClose: () => void
}

export function AiTravelSidebar({ destination, isOpen, onClose }: AiTravelSidebarProps) {
  const [plan, setPlan] = useState<TravelPlan | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (destination && isOpen) {
      setLoading(true)
      setPlan(null)
      setError(null)
      generateItinerary(destination)
        .then(data => setPlan(data))
        .catch(err => {
          console.error(err)
          setError("Oops! Failed to connect to AI service. Please try again.")
        })
        .finally(() => setLoading(false))
    }
  }, [destination, isOpen])

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto sm:rounded-[2rem] bg-white/95 dark:bg-gray-950/95 backdrop-blur-2xl border-white/20 shadow-2xl">
        <DialogHeader className="mb-6">
          <DialogTitle className="flex items-center text-3xl font-black gap-3 text-transparent bg-clip-text bg-gradient-to-r from-primary to-cyan-600">
            {destination ? (
              <>
                <Sparkles className="text-primary h-8 w-8" />
                AI Itinerary for {destination.name}
              </>
            ) : "Loading..."}
          </DialogTitle>
          <DialogDescription className="text-lg mt-2 font-medium">
            Your personalized 3-day travel plan generated by TraveLens AI.
          </DialogDescription>
        </DialogHeader>
        
        <div className="mt-2">
          {error && (
            <div className="flex justify-center py-6">
              <div className="bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-400 p-4 rounded-xl border border-red-200 dark:border-red-800 text-center max-w-sm w-full mx-auto shadow-sm">
                <p className="font-semibold">{error}</p>
                 <button onClick={() => setError(null)} className="mt-2 text-sm underline opacity-80 hover:opacity-100">Dismiss</button>
              </div>
            </div>
          )}
          
          {loading && (
            <div className="flex flex-col items-center justify-center py-20 space-y-6 text-primary">
              <Loader2 className="h-12 w-12 animate-spin" />
              <p className="animate-pulse text-xl font-medium">Crafting your perfect journey...</p>
            </div>
          )}
          
          {plan && !loading && (
            <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-primary before:via-cyan-400 before:to-transparent">
              {plan.days.map((item, index) => (
                <div key={item.day} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full border-4 border-white dark:border-gray-950 bg-primary text-white font-bold shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 shadow-md relative z-10">
                    {item.day}
                  </div>
                  <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] p-6 rounded-2xl bg-white dark:bg-gray-900 shadow-lg border border-gray-100 dark:border-gray-800">
                    <h4 className="text-xl font-bold flex items-center gap-2 mb-3 text-gray-800 dark:text-gray-100">
                      <CalendarDays className="h-5 w-5 text-cyan-500" />
                      {item.title}
                    </h4>
                    <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                      {item.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
